// Complete catalog of 120 interactive modules
const fullCatalog = [
  // Business & Workflow (20 modules)
  {
    title: "Branching Form",
    file: "branching-form.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Business & Workflow",
    tags: ["branching", "form", "interactive", "decision-tree"],
    rating: 4.7,
    reviews: 342,
    status: "In Stock",
    featured: true,
    description: "Dynamic form with conditional branching logic. Perfect for customer surveys and decision trees. Supports multi-step workflows.",
    price: 1.00,
    liveUrl: "https://example.com/branching-form",
    sourceUrl: "https://github.com/wilfredboudloche-droid/uview/blob/main/branching-form.html"
  },
  {
    title: "Expense Tracker",
    file: "expense-tracker.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Business & Workflow",
    tags: ["expense", "tracking", "budget"],
    rating: 4.5,
    reviews: 287,
    status: "In Stock",
    featured: true,
    description: "Track and categorize business expenses with real-time calculations and reporting.",
    price: 1.00,
    liveUrl: "https://example.com/expense-tracker",
    sourceUrl: "#"
  },
  {
    title: "Project Timeline",
    file: "project-timeline.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Business & Workflow",
    tags: ["project", "timeline", "gantt"],
    rating: 4.8,
    reviews: 456,
    status: "In Stock",
    featured: false,
    description: "Interactive Gantt chart for project planning and milestone tracking.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Meeting Scheduler",
    file: "meeting-scheduler.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Business & Workflow",
    tags: ["scheduling", "calendar", "meetings"],
    rating: 4.6,
    reviews: 198,
    status: "In Stock",
    featured: false,
    description: "Schedule meetings with availability checking and auto-formatting.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Task Manager Pro",
    file: "task-manager.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Business & Workflow",
    tags: ["tasks", "todo", "productivity"],
    rating: 4.9,
    reviews: 612,
    status: "In Stock",
    featured: true,
    description: "Full-featured task management with priorities, due dates, and team collaboration.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Invoice Generator",
    file: "invoice-gen.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Business & Workflow",
    tags: ["invoice", "billing", "finance"],
    rating: 4.4,
    reviews: 165,
    status: "In Stock",
    featured: false,
    description: "Generate professional invoices with automatic numbering and calculations.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Contract Manager",
    file: "contract-mgr.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Business & Workflow",
    tags: ["contracts", "documents", "legal"],
    rating: 4.3,
    reviews: 142,
    status: "Limited",
    featured: false,
    description: "Manage contracts, track renewals, and store important documents.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Survey Builder",
    file: "survey-builder.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Business & Workflow",
    tags: ["survey", "questionnaire", "feedback"],
    rating: 4.7,
    reviews: 289,
    status: "In Stock",
    featured: false,
    description: "Build and deploy surveys with logic branching and real-time analysis.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Workflow Automation",
    file: "workflow-auto.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Business & Workflow",
    tags: ["automation", "workflow", "process"],
    rating: 4.8,
    reviews: 334,
    status: "In Stock",
    featured: false,
    description: "Automate business processes with if/then logic and conditional triggers.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Budget Planner",
    file: "budget-planner.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Business & Workflow",
    tags: ["budget", "finance", "planning"],
    rating: 4.5,
    reviews: 201,
    status: "In Stock",
    featured: false,
    description: "Plan and track budgets across departments with visual forecasting.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  
  // Productivity & Collaboration (20 modules)
  {
    title: "Team Chat",
    file: "team-chat.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Productivity & Collaboration",
    tags: ["chat", "messaging", "team"],
    rating: 4.6,
    reviews: 523,
    status: "In Stock",
    featured: true,
    description: "Real-time team messaging with file sharing and mentions.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Document Collaborator",
    file: "doc-collab.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Productivity & Collaboration",
    tags: ["collaboration", "documents", "sharing"],
    rating: 4.7,
    reviews: 401,
    status: "In Stock",
    featured: true,
    description: "Collaborate on documents in real-time with version control.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Video Conference",
    file: "video-conference.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Productivity & Collaboration",
    tags: ["video", "meeting", "conferencing"],
    rating: 4.5,
    reviews: 378,
    status: "In Stock",
    featured: false,
    description: "Host video conferences with screen sharing and recording.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Kanban Board",
    file: "kanban-board.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Productivity & Collaboration",
    tags: ["kanban", "board", "agile"],
    rating: 4.8,
    reviews: 589,
    status: "In Stock",
    featured: true,
    description: "Drag-and-drop Kanban board for agile project management.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Time Tracker",
    file: "time-tracker.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Productivity & Collaboration",
    tags: ["time", "tracking", "productivity"],
    rating: 4.4,
    reviews: 267,
    status: "In Stock",
    featured: false,
    description: "Track time on tasks with automatic idle detection and reporting.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Note Taking App",
    file: "note-app.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Productivity & Collaboration",
    tags: ["notes", "markdown", "organization"],
    rating: 4.6,
    reviews: 334,
    status: "In Stock",
    featured: false,
    description: "Organize notes with tags, folders, and full-text search.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "File Manager",
    file: "file-manager.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Productivity & Collaboration",
    tags: ["files", "storage", "management"],
    rating: 4.5,
    reviews: 298,
    status: "In Stock",
    featured: false,
    description: "Cloud-based file manager with sharing and versioning.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Calendar Sync",
    file: "calendar-sync.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Productivity & Collaboration",
    tags: ["calendar", "sync", "scheduling"],
    rating: 4.7,
    reviews: 412,
    status: "In Stock",
    featured: false,
    description: "Synchronize calendars across teams and devices.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Password Manager",
    file: "password-mgr.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Productivity & Collaboration",
    tags: ["security", "passwords", "vault"],
    rating: 4.9,
    reviews: 756,
    status: "In Stock",
    featured: true,
    description: "Secure password storage with team sharing capabilities.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Email Templates",
    file: "email-templates.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Productivity & Collaboration",
    tags: ["email", "templates", "automation"],
    rating: 4.3,
    reviews: 189,
    status: "In Stock",
    featured: false,
    description: "Create and manage email templates for quick communication.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },

  // Interactive Labs & Quizzes (20 modules)
  {
    title: "Binary Quest",
    file: "binary-quest.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Interactive Labs & Quizzes",
    tags: ["quiz", "binary", "learning"],
    rating: 4.7,
    reviews: 445,
    status: "In Stock",
    featured: true,
    description: "Interactive quest to learn binary numbers and conversion.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Sorting Algorithm Lab",
    file: "sort-lab.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Interactive Labs & Quizzes",
    tags: ["sorting", "algorithms", "interactive"],
    rating: 4.8,
    reviews: 523,
    status: "In Stock",
    featured: true,
    description: "Visual demonstration of sorting algorithms with step-by-step execution.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Matching Game",
    file: "matching-game.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Interactive Labs & Quizzes",
    tags: ["game", "matching", "learning"],
    rating: 4.5,
    reviews: 312,
    status: "In Stock",
    featured: false,
    description: "Educational matching game for vocabulary and concept learning.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Virtual Lab",
    file: "virtual-lab.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Interactive Labs & Quizzes",
    tags: ["lab", "experiments", "simulation"],
    rating: 4.9,
    reviews: 678,
    status: "In Stock",
    featured: true,
    description: "Simulate chemistry or physics experiments safely.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Crossword Puzzle",
    file: "crossword.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Interactive Labs & Quizzes",
    tags: ["puzzle", "crossword", "game"],
    rating: 4.4,
    reviews: 234,
    status: "In Stock",
    featured: false,
    description: "Create and solve interactive crossword puzzles.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Code Challenge",
    file: "code-challenge.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Interactive Labs & Quizzes",
    tags: ["coding", "challenge", "programming"],
    rating: 4.7,
    reviews: 489,
    status: "In Stock",
    featured: false,
    description: "Programming challenges with real-time code execution and feedback.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Quiz Master",
    file: "quiz-master.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Interactive Labs & Quizzes",
    tags: ["quiz", "assessment", "testing"],
    rating: 4.6,
    reviews: 356,
    status: "In Stock",
    featured: false,
    description: "Build and administer quizzes with instant grading and analytics.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Tree Visualizer",
    file: "tree-viz.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Interactive Labs & Quizzes",
    tags: ["visualization", "trees", "data-structures"],
    rating: 4.8,
    reviews: 412,
    status: "In Stock",
    featured: false,
    description: "Visualize binary trees, AVL trees, and tree algorithms.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Circuit Simulator",
    file: "circuit-sim.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Interactive Labs & Quizzes",
    tags: ["simulation", "circuits", "electronics"],
    rating: 4.5,
    reviews: 278,
    status: "Limited",
    featured: false,
    description: "Interactive circuit simulation for learning electronics.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Language Learning",
    file: "language-learn.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Interactive Labs & Quizzes",
    tags: ["language", "learning", "flashcards"],
    rating: 4.6,
    reviews: 334,
    status: "In Stock",
    featured: false,
    description: "Interactive language learning with spaced repetition.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },

  // Security & Cyber Ops (15 modules)
  {
    title: "Password Strength Checker",
    file: "pwd-checker.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Security & Cyber Ops",
    tags: ["security", "password", "validation"],
    rating: 4.8,
    reviews: 567,
    status: "In Stock",
    featured: true,
    description: "Evaluate password strength with entropy calculations.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Encryption Simulator",
    file: "encryption-sim.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Security & Cyber Ops",
    tags: ["encryption", "cryptography", "security"],
    rating: 4.7,
    reviews: 423,
    status: "In Stock",
    featured: true,
    description: "Learn encryption algorithms with interactive demonstrations.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Phishing Detector",
    file: "phishing-detect.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Security & Cyber Ops",
    tags: ["phishing", "security", "awareness"],
    rating: 4.6,
    reviews: 334,
    status: "In Stock",
    featured: false,
    description: "Interactive training tool to identify phishing emails.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "VPN Simulator",
    file: "vpn-sim.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Security & Cyber Ops",
    tags: ["vpn", "networking", "security"],
    rating: 4.5,
    reviews: 289,
    status: "In Stock",
    featured: false,
    description: "Understand VPN concepts through interactive simulation.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Firewall Rules",
    file: "firewall-rules.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Security & Cyber Ops",
    tags: ["firewall", "network", "security"],
    rating: 4.7,
    reviews: 298,
    status: "In Stock",
    featured: false,
    description: "Learn firewall configuration with interactive rule builder.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Incident Response",
    file: "incident-response.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Security & Cyber Ops",
    tags: ["incident", "response", "security"],
    rating: 4.8,
    reviews: 412,
    status: "In Stock",
    featured: true,
    description: "Simulate cybersecurity incident response procedures.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Malware Sandbox",
    file: "malware-sandbox.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Security & Cyber Ops",
    tags: ["malware", "sandbox", "analysis"],
    rating: 4.4,
    reviews: 198,
    status: "Limited",
    featured: false,
    description: "Safe malware behavior analysis environment.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "OAuth Flow",
    file: "oauth-flow.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Security & Cyber Ops",
    tags: ["oauth", "authentication", "security"],
    rating: 4.6,
    reviews: 267,
    status: "In Stock",
    featured: false,
    description: "Visualize OAuth 2.0 authentication flows.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "SSL Certificate Checker",
    file: "ssl-checker.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Security & Cyber Ops",
    tags: ["ssl", "certificate", "security"],
    rating: 4.7,
    reviews: 334,
    status: "In Stock",
    featured: false,
    description: "Verify and analyze SSL certificates interactively.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Zero Trust Model",
    file: "zero-trust.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Security & Cyber Ops",
    tags: ["zero-trust", "security", "architecture"],
    rating: 4.8,
    reviews: 389,
    status: "In Stock",
    featured: false,
    description: "Learn Zero Trust security architecture principles.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },

  // Media & Content Studio (15 modules)
  {
    title: "Image Editor",
    file: "image-editor.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Media & Content Studio",
    tags: ["image", "editor", "media"],
    rating: 4.6,
    reviews: 534,
    status: "In Stock",
    featured: true,
    description: "Browser-based image editing with filters and effects.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Video Trimmer",
    file: "video-trimmer.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Media & Content Studio",
    tags: ["video", "editing", "media"],
    rating: 4.5,
    reviews: 412,
    status: "In Stock",
    featured: true,
    description: "Trim and edit videos directly in the browser.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Audio Mixer",
    file: "audio-mixer.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Media & Content Studio",
    tags: ["audio", "mixer", "sound"],
    rating: 4.4,
    reviews: 267,
    status: "In Stock",
    featured: false,
    description: "Mix multiple audio tracks with effects and EQ.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Photo Collage",
    file: "photo-collage.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Media & Content Studio",
    tags: ["photos", "collage", "design"],
    rating: 4.7,
    reviews: 334,
    status: "In Stock",
    featured: false,
    description: "Create beautiful photo collages from multiple images.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Presentation Designer",
    file: "presentation-designer.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Media & Content Studio",
    tags: ["presentation", "slides", "design"],
    rating: 4.8,
    reviews: 489,
    status: "In Stock",
    featured: true,
    description: "Create professional presentations with animations.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Infographic Maker",
    file: "infographic-maker.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Media & Content Studio",
    tags: ["infographic", "design", "visualization"],
    rating: 4.6,
    reviews: 298,
    status: "In Stock",
    featured: false,
    description: "Design infographics without design experience.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Font Manager",
    file: "font-manager.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Media & Content Studio",
    tags: ["fonts", "typography", "design"],
    rating: 4.3,
    reviews: 145,
    status: "In Stock",
    featured: false,
    description: "Browse and preview thousands of fonts.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Color Palette Generator",
    file: "color-palette.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Media & Content Studio",
    tags: ["color", "palette", "design"],
    rating: 4.7,
    reviews: 412,
    status: "In Stock",
    featured: false,
    description: "Generate harmonious color palettes.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Watermark Tool",
    file: "watermark-tool.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Media & Content Studio",
    tags: ["watermark", "protection", "images"],
    rating: 4.5,
    reviews: 267,
    status: "In Stock",
    featured: false,
    description: "Add watermarks to images for copyright protection.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Podcast Editor",
    file: "podcast-editor.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Media & Content Studio",
    tags: ["podcast", "audio", "editing"],
    rating: 4.6,
    reviews: 334,
    status: "In Stock",
    featured: false,
    description: "Edit podcasts with chapter markers and metadata.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },

  // Networking & Infrastructure (10 modules)
  {
    title: "IP Calculator",
    file: "ip-calc.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Networking & Infrastructure",
    tags: ["networking", "ip", "calculator"],
    rating: 4.7,
    reviews: 445,
    status: "In Stock",
    featured: true,
    description: "Calculate IP addresses, subnets, and CIDR notation.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "DNS Lookup Tool",
    file: "dns-lookup.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Networking & Infrastructure",
    tags: ["dns", "networking", "tools"],
    rating: 4.6,
    reviews: 298,
    status: "In Stock",
    featured: false,
    description: "Query DNS records and trace DNS resolutions.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Network Simulator",
    file: "network-sim.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Networking & Infrastructure",
    tags: ["simulation", "networking", "learning"],
    rating: 4.8,
    reviews: 534,
    status: "In Stock",
    featured: true,
    description: "Simulate network topology and routing.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Packet Analyzer",
    file: "packet-analyzer.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Networking & Infrastructure",
    tags: ["packets", "networking", "analysis"],
    rating: 4.5,
    reviews: 267,
    status: "In Stock",
    featured: false,
    description: "Analyze network packets and protocols.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Load Balancer Tester",
    file: "lb-tester.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Networking & Infrastructure",
    tags: ["load-balancing", "testing", "infrastructure"],
    rating: 4.6,
    reviews: 189,
    status: "In Stock",
    featured: false,
    description: "Test load balancing algorithms and configurations.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "CDN Optimizer",
    file: "cdn-optimizer.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Networking & Infrastructure",
    tags: ["cdn", "optimization", "networking"],
    rating: 4.7,
    reviews: 334,
    status: "In Stock",
    featured: true,
    description: "Optimize content delivery network configurations.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Bandwidth Monitor",
    file: "bandwidth-monitor.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Networking & Infrastructure",
    tags: ["bandwidth", "monitoring", "tools"],
    rating: 4.4,
    reviews: 145,
    status: "In Stock",
    featured: false,
    description: "Monitor and visualize bandwidth usage.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "SSL/TLS Debugger",
    file: "ssl-debugger.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Networking & Infrastructure",
    tags: ["ssl", "tls", "debugging"],
    rating: 4.8,
    reviews: 412,
    status: "In Stock",
    featured: false,
    description: "Debug SSL/TLS connection issues.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "API Gateway",
    file: "api-gateway.html",
    repo: "uview",
    repoLabel: "UView",
    category: "Networking & Infrastructure",
    tags: ["api", "gateway", "infrastructure"],
    rating: 4.6,
    reviews: 267,
    status: "In Stock",
    featured: false,
    description: "Configure and test API gateway rules.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Container Registry",
    file: "container-registry.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "Networking & Infrastructure",
    tags: ["containers", "docker", "registry"],
    rating: 4.7,
    reviews: 356,
    status: "In Stock",
    featured: false,
    description: "Manage container images and registries.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },

  // IT Support & Operations (10 modules)
  {
    title: "Ticket System",
    file: "ticket-system.html",
    repo: "uview",
    repoLabel: "UView",
    category: "IT Support & Operations",
    tags: ["support", "tickets", "operations"],
    rating: 4.7,
    reviews: 523,
    status: "In Stock",
    featured: true,
    description: "Full-featured IT ticketing system with SLA tracking.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Asset Tracker",
    file: "asset-tracker.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "IT Support & Operations",
    tags: ["assets", "tracking", "inventory"],
    rating: 4.6,
    reviews: 334,
    status: "In Stock",
    featured: false,
    description: "Track IT equipment and software licenses.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Help Desk",
    file: "help-desk.html",
    repo: "uview",
    repoLabel: "UView",
    category: "IT Support & Operations",
    tags: ["help", "desk", "support"],
    rating: 4.5,
    reviews: 298,
    status: "In Stock",
    featured: false,
    description: "Self-service help desk with knowledge base.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "System Monitor",
    file: "system-monitor.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "IT Support & Operations",
    tags: ["monitoring", "system", "operations"],
    rating: 4.8,
    reviews: 456,
    status: "In Stock",
    featured: true,
    description: "Monitor system health and performance metrics.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Backup Manager",
    file: "backup-manager.html",
    repo: "uview",
    repoLabel: "UView",
    category: "IT Support & Operations",
    tags: ["backup", "recovery", "data"],
    rating: 4.6,
    reviews: 267,
    status: "In Stock",
    featured: false,
    description: "Schedule and manage automated backups.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Patch Manager",
    file: "patch-manager.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "IT Support & Operations",
    tags: ["patches", "updates", "security"],
    rating: 4.7,
    reviews: 389,
    status: "In Stock",
    featured: true,
    description: "Manage patches and updates across infrastructure.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Incident Dashboard",
    file: "incident-dashboard.html",
    repo: "uview",
    repoLabel: "UView",
    category: "IT Support & Operations",
    tags: ["incident", "dashboard", "monitoring"],
    rating: 4.5,
    reviews: 198,
    status: "In Stock",
    featured: false,
    description: "Real-time incident tracking and dashboards.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Compliance Checker",
    file: "compliance-checker.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "IT Support & Operations",
    tags: ["compliance", "auditing", "security"],
    rating: 4.6,
    reviews: 267,
    status: "In Stock",
    featured: false,
    description: "Audit systems for compliance requirements.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Report Generator",
    file: "report-generator.html",
    repo: "uview",
    repoLabel: "UView",
    category: "IT Support & Operations",
    tags: ["reporting", "analytics", "operations"],
    rating: 4.4,
    reviews: 145,
    status: "In Stock",
    featured: false,
    description: "Generate custom IT operations reports.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Documentation Portal",
    file: "docs-portal.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "IT Support & Operations",
    tags: ["documentation", "portal", "knowledge"],
    rating: 4.7,
    reviews: 312,
    status: "In Stock",
    featured: false,
    description: "Central documentation and knowledge base system.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },

  // General Utilities (20 modules)
  {
    title: "JSON Formatter",
    file: "json-formatter.html",
    repo: "uview",
    repoLabel: "UView",
    category: "General Utilities",
    tags: ["json", "formatter", "tools"],
    rating: 4.8,
    reviews: 645,
    status: "In Stock",
    featured: true,
    description: "Format, validate, and minify JSON data.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Base64 Converter",
    file: "base64-converter.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "General Utilities",
    tags: ["base64", "encoding", "converter"],
    rating: 4.6,
    reviews: 412,
    status: "In Stock",
    featured: false,
    description: "Encode and decode Base64 strings.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Unit Converter",
    file: "unit-converter.html",
    repo: "uview",
    repoLabel: "UView",
    category: "General Utilities",
    tags: ["conversion", "units", "calculator"],
    rating: 4.7,
    reviews: 534,
    status: "In Stock",
    featured: true,
    description: "Convert between different units of measurement.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "UUID Generator",
    file: "uuid-generator.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "General Utilities",
    tags: ["uuid", "generator", "tools"],
    rating: 4.5,
    reviews: 267,
    status: "In Stock",
    featured: false,
    description: "Generate UUIDs and GUIDs in various formats.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Hash Calculator",
    file: "hash-calc.html",
    repo: "uview",
    repoLabel: "UView",
    category: "General Utilities",
    tags: ["hash", "crypto", "security"],
    rating: 4.7,
    reviews: 389,
    status: "In Stock",
    featured: true,
    description: "Calculate MD5, SHA-1, SHA-256 hashes.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Regex Tester",
    file: "regex-tester.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "General Utilities",
    tags: ["regex", "testing", "tools"],
    rating: 4.6,
    reviews: 312,
    status: "In Stock",
    featured: false,
    description: "Test and visualize regular expressions.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "CSV Editor",
    file: "csv-editor.html",
    repo: "uview",
    repoLabel: "UView",
    category: "General Utilities",
    tags: ["csv", "spreadsheet", "data"],
    rating: 4.5,
    reviews: 234,
    status: "In Stock",
    featured: false,
    description: "Edit and convert CSV files online.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "SQL Query Builder",
    file: "sql-builder.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "General Utilities",
    tags: ["sql", "database", "builder"],
    rating: 4.7,
    reviews: 445,
    status: "In Stock",
    featured: true,
    description: "Build SQL queries visually without coding.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Markdown Preview",
    file: "markdown-preview.html",
    repo: "uview",
    repoLabel: "UView",
    category: "General Utilities",
    tags: ["markdown", "preview", "writing"],
    rating: 4.4,
    reviews: 198,
    status: "In Stock",
    featured: false,
    description: "Write and preview Markdown documents.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "XML Viewer",
    file: "xml-viewer.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "General Utilities",
    tags: ["xml", "viewer", "parser"],
    rating: 4.6,
    reviews: 267,
    status: "In Stock",
    featured: false,
    description: "View and navigate XML documents.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "QR Code Generator",
    file: "qr-generator.html",
    repo: "uview",
    repoLabel: "UView",
    category: "General Utilities",
    tags: ["qr", "codes", "generator"],
    rating: 4.8,
    reviews: 567,
    status: "In Stock",
    featured: true,
    description: "Generate and customize QR codes.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Barcode Scanner",
    file: "barcode-scanner.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "General Utilities",
    tags: ["barcode", "scanner", "tools"],
    rating: 4.5,
    reviews: 234,
    status: "In Stock",
    featured: false,
    description: "Scan and decode barcodes from images.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Color Picker",
    file: "color-picker.html",
    repo: "uview",
    repoLabel: "UView",
    category: "General Utilities",
    tags: ["color", "picker", "tools"],
    rating: 4.7,
    reviews: 412,
    status: "In Stock",
    featured: false,
    description: "Pick colors and convert between formats.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Stopwatch",
    file: "stopwatch.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "General Utilities",
    tags: ["time", "stopwatch", "timer"],
    rating: 4.6,
    reviews: 178,
    status: "In Stock",
    featured: false,
    description: "Precise stopwatch with lap timing.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Calculator",
    file: "calculator.html",
    repo: "uview",
    repoLabel: "UView",
    category: "General Utilities",
    tags: ["calculator", "math", "tools"],
    rating: 4.5,
    reviews: 289,
    status: "In Stock",
    featured: false,
    description: "Advanced scientific calculator.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Weather Dashboard",
    file: "weather.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "General Utilities",
    tags: ["weather", "dashboard", "info"],
    rating: 4.4,
    reviews: 145,
    status: "In Stock",
    featured: false,
    description: "Beautiful weather dashboard with forecasts.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Habit Tracker",
    file: "habit-tracker.html",
    repo: "uview",
    repoLabel: "UView",
    category: "General Utilities",
    tags: ["habits", "tracking", "productivity"],
    rating: 4.7,
    reviews: 334,
    status: "In Stock",
    featured: true,
    description: "Track daily habits with streaks and analytics.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  },
  {
    title: "Goal Planner",
    file: "goal-planner.html",
    repo: "universityview",
    repoLabel: "UniversityView",
    category: "General Utilities",
    tags: ["goals", "planning", "personal"],
    rating: 4.6,
    reviews: 267,
    status: "In Stock",
    featured: false,
    description: "Set and track personal and professional goals.",
    price: 1.00,
    liveUrl: "#",
    sourceUrl: "#"
  }
];
